Q1. How many missing values are in each column?

Q2. Find the percentage of missing values in each column.

Q3. Drop all rows that contain missing values.

Q4. Drop all columns that contain missing values.

Q5. Fill the missing values in the "Salary" column with the mean of that column.

Q6. Fill the missing values in the "Age" column with the median.

Q7. Forward fill the missing values in the "Department" column.

In [1]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika', 'Pari', 'Rishabh', 
                      'Neha', 'Vikram', 'Sneha', 'Arjun', 'Priya'],
    'Age': [24, np.nan, 20, 20, 19, 28, np.nan, 25, 27, 22],
    'Department': ['Marketing', 'IT', None, 'IT', 'HR', 
                   'Finance', 'Marketing', None, 'IT', 'Finance'],
    'Salary': [35000, 80000, np.nan, 55000, 60000, 
               90000, 72000, 48000, np.nan, 67000],
    'City': ['Delhi', 'Mumbai', 'Pune', None, 'Bangalore',
             'Mumbai', None, 'Pune', 'Bangalore', 'Mumbai'],
    'Experience': [2, 1, 0, np.nan, 1, 5, 8, 3, np.nan, 1]
})
data

  Employee Name   Age Department   Salary       City  Experience
0           Raj  24.0  Marketing  35000.0      Delhi         2.0
1         Ayush   NaN         IT  80000.0     Mumbai         1.0
2       Anamika  20.0       None      NaN       Pune         0.0
3          Pari  20.0         IT  55000.0       None         NaN
4       Rishabh  19.0         HR  60000.0  Bangalore         1.0
5          Neha  28.0    Finance  90000.0     Mumbai         5.0
6        Vikram   NaN  Marketing  72000.0       None         8.0
7         Sneha  25.0       None  48000.0       Pune         3.0
8         Arjun  27.0         IT      NaN  Bangalore         NaN
9         Priya  22.0    Finance  67000.0     Mumbai         1.0

Q1. How many missing values are in each column?

In [2]:
data.isnull().sum()

Employee Name    0
Age              2
Department       2
Salary           2
City             2
Experience       2
dtype: int64

Q2. Find the percentage of missing values in each column.

In [3]:
data.isnull().mean() * 100

Employee Name     0.0
Age              20.0
Department       20.0
Salary           20.0
City             20.0
Experience       20.0
dtype: float64

Q3. Drop all rows that contain missing values

In [4]:
data.dropna()

  Employee Name   Age Department   Salary       City  Experience
0           Raj  24.0  Marketing  35000.0      Delhi         2.0
4       Rishabh  19.0         HR  60000.0  Bangalore         1.0
5          Neha  28.0    Finance  90000.0     Mumbai         5.0
9         Priya  22.0    Finance  67000.0     Mumbai         1.0

Q4. Drop all columns that contain missing values.

In [5]:
data.dropna(axis=1)

  Employee Name
0           Raj
1         Ayush
2       Anamika
3          Pari
4       Rishabh
5          Neha
6        Vikram
7         Sneha
8         Arjun
9         Priya

Q5. Fill the missing values in the "Salary" column with the mean of that column.

In [ ]:
data['Salary'].fillna(data['Salary'].mean())

0    35000.0
1    80000.0
2    63375.0
3    55000.0
4    60000.0
5    90000.0
6    72000.0
7    48000.0
8    63375.0
9    67000.0
Name: Salary, dtype: float64

Q6. Fill the missing values in the "Age" column with the median.

In [11]:
data['Age'].fillna(data['Age'].median())

0    24.0
1    23.0
2    20.0
3    20.0
4    19.0
5    28.0
6    23.0
7    25.0
8    27.0
9    22.0
Name: Age, dtype: float64

Q7. Forward fill the missing values in the "Department" column.

In [15]:
data['Department'].ffill()

0    Marketing
1           IT
2           IT
3           IT
4           HR
5      Finance
6    Marketing
7    Marketing
8           IT
9      Finance
Name: Department, dtype: object