Q1. Find the maximum, minimum, mean, and standard deviation of the Salary column.

Q2. Calculate descriptive statistics for all numeric columns at once using describe().

Q3. Sort the DataFrame by Salary in ascending order.

Q4. Sort the same DataFrame by Salary in descending order.

Q5. Filter employees with a salary greater than 50,000.

Q6. Filter employees whose age is between 20 and 24 (use the & operator).

Q7. Filter employees working in the IT department.

Q8. Filter employees who belong to the IT department OR have a salary greater than 60,000 (use the | operator).

Q9. Select the first 3 rows and only the Name and Salary columns using .loc.

Q10. Select the last 2 rows using .iloc.

In [2]:
import pandas as pd
data = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika', 'Pari', 'Rishabh',
                      'Neha', 'Vikram', 'Sneha', 'Arjun', 'Priya'],
    'Age': [24, 23, 20, 20, 19, 28, 32, 25, 27, 22],
    'Department': ['Marketing', 'IT', 'IT', 'IT', 'HR', 
                   'Finance', 'Marketing', 'HR', 'IT', 'Finance'],
    'Salary': [35000, 80000, 75000, 55000, 60000, 
               90000, 72000, 48000, 85000, 67000],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Bangalore',
             'Mumbai', 'Delhi', 'Pune', 'Bangalore', 'Mumbai'],
    'Experience': [2, 1, 0, 0, 1, 5, 8, 3, 4, 1]
})
data

  Employee Name  Age Department  Salary       City  Experience
0           Raj   24  Marketing   35000      Delhi           2
1         Ayush   23         IT   80000     Mumbai           1
2       Anamika   20         IT   75000       Pune           0
3          Pari   20         IT   55000      Delhi           0
4       Rishabh   19         HR   60000  Bangalore           1
5          Neha   28    Finance   90000     Mumbai           5
6        Vikram   32  Marketing   72000      Delhi           8
7         Sneha   25         HR   48000       Pune           3
8         Arjun   27         IT   85000  Bangalore           4
9         Priya   22    Finance   67000     Mumbai           1

Q1. Find the maximum, minimum, mean, and standard deviation of the Salary column.

In [17]:
data['Salary'].agg(['max','min','mean','std'])

max     90000.000000
min     35000.000000
mean    66700.000000
std     17282.296658
Name: Salary, dtype: float64

Q2. Calculate descriptive statistics for all numeric columns at once using describe().

In [20]:
data[['Age','Salary','Experience']].describe()

             Age        Salary  Experience
count  10.000000     10.000000    10.00000
mean   24.000000  66700.000000     2.50000
std     4.109609  17282.296658     2.54951
min    19.000000  35000.000000     0.00000
25%    20.500000  56250.000000     1.00000
50%    23.500000  69500.000000     1.50000
75%    26.500000  78750.000000     3.75000
max    32.000000  90000.000000     8.00000

Q3. Sort the DataFrame by Salary in ascending order.

In [26]:
data.sort_values(by='Salary', ascending=True)

  Employee Name  Age Department  Salary       City  Experience
0           Raj   24  Marketing   35000      Delhi           2
7         Sneha   25         HR   48000       Pune           3
3          Pari   20         IT   55000      Delhi           0
4       Rishabh   19         HR   60000  Bangalore           1
9         Priya   22    Finance   67000     Mumbai           1
6        Vikram   32  Marketing   72000      Delhi           8
2       Anamika   20         IT   75000       Pune           0
1         Ayush   23         IT   80000     Mumbai           1
8         Arjun   27         IT   85000  Bangalore           4
5          Neha   28    Finance   90000     Mumbai           5

Q4. Sort the same DataFrame by Salary in descending order.

In [28]:
data.sort_values(by='Salary', ascending=False)

  Employee Name  Age Department  Salary       City  Experience
5          Neha   28    Finance   90000     Mumbai           5
8         Arjun   27         IT   85000  Bangalore           4
1         Ayush   23         IT   80000     Mumbai           1
2       Anamika   20         IT   75000       Pune           0
6        Vikram   32  Marketing   72000      Delhi           8
9         Priya   22    Finance   67000     Mumbai           1
4       Rishabh   19         HR   60000  Bangalore           1
3          Pari   20         IT   55000      Delhi           0
7         Sneha   25         HR   48000       Pune           3
0           Raj   24  Marketing   35000      Delhi           2

Q5. Filter employees with a salary greater than 50,000.

In [38]:
data[data['Salary'] > 50000]

  Employee Name  Age Department  Salary       City  Experience
3          Pari   20         IT   55000      Delhi           0
4       Rishabh   19         HR   60000  Bangalore           1
9         Priya   22    Finance   67000     Mumbai           1
6        Vikram   32  Marketing   72000      Delhi           8
2       Anamika   20         IT   75000       Pune           0
1         Ayush   23         IT   80000     Mumbai           1
8         Arjun   27         IT   85000  Bangalore           4
5          Neha   28    Finance   90000     Mumbai           5

Q6. Filter employees whose age is between 20 and 24 (use the & operator).

In [41]:
data[(data["Age"] >= 20) & (data["Age"] <=24)]

  Employee Name  Age Department  Salary    City  Experience
0           Raj   24  Marketing   35000   Delhi           2
3          Pari   20         IT   55000   Delhi           0
9         Priya   22    Finance   67000  Mumbai           1
2       Anamika   20         IT   75000    Pune           0
1         Ayush   23         IT   80000  Mumbai           1

Q7. Filter employees working in the IT department.

In [46]:
data[data["Department"]== 'IT']

  Employee Name  Age Department  Salary       City  Experience
3          Pari   20         IT   55000      Delhi           0
2       Anamika   20         IT   75000       Pune           0
1         Ayush   23         IT   80000     Mumbai           1
8         Arjun   27         IT   85000  Bangalore           4

Q8. Filter employees who belong to the IT department OR have a salary greater than 60,000 (use the | operator).

In [48]:
data[(data["Department"]== 'IT') | (data["Salary"] >= 60000)]

  Employee Name  Age Department  Salary       City  Experience
3          Pari   20         IT   55000      Delhi           0
4       Rishabh   19         HR   60000  Bangalore           1
9         Priya   22    Finance   67000     Mumbai           1
6        Vikram   32  Marketing   72000      Delhi           8
2       Anamika   20         IT   75000       Pune           0
1         Ayush   23         IT   80000     Mumbai           1
8         Arjun   27         IT   85000  Bangalore           4
5          Neha   28    Finance   90000     Mumbai           5

Q9. Select the first 3 rows and only the Name and Salary columns using .loc.

In [74]:
data = data.reset_index(drop=True)
data.loc[0:2,['Employee Name','Salary']]

  Employee Name  Salary
0           Raj   35000
1         Sneha   48000
2          Pari   55000

Q10. Select the last 2 rows using .iloc.

In [ ]:
data.iloc[-2:]

  Employee Name  Age Department  Salary       City  Experience
0           Raj   24  Marketing   35000      Delhi           2
1         Sneha   25         HR   48000       Pune           3
2          Pari   20         IT   55000      Delhi           0
3       Rishabh   19         HR   60000  Bangalore           1
4         Priya   22    Finance   67000     Mumbai           1
5        Vikram   32  Marketing   72000      Delhi           8
6       Anamika   20         IT   75000       Pune           0
7         Ayush   23         IT   80000     Mumbai           1