* **Q1.** First, manually insert $2\text{--}3$ values of `-99999` into the DataFrame, then replace them with `np.nan`.
* **Q2.** Convert the values in the `Employee Name` column to lowercase using `str.lower()`.
* **Q3.** Remove leading and trailing spaces from the `City` column using `str.strip()`. (First, manually add extra spaces to a few values).
* **Q4.** Find duplicate rows using `duplicated()`.
* **Q5.** Remove duplicate rows using `drop_duplicates()`.
* **Q6.** Convert all values in the `Department` column to uppercase using `str.upper()`.
* **Q7.** Convert the `Salary` column from string to numeric — first manually convert a few values to strings using `astype(str)`, and then convert them back to numeric using `pd.to_numeric()`.

Q1. First, manually insert $2\text{--}3$ values of -99999 into the DataFrame, then replace them with np.nan.

In [71]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika', 'Pari', 'Rishabh',
                      'Neha', 'Vikram', 'Sneha', 'Arjun', 'Priya'],
    'Age': [24, np.nan, 20, 20, 19, 28, np.nan, 25, 27, 22],
    'Department': ['Marketing', 'IT', None, 'IT', 'HR',
                   'Finance', 'Marketing', None, 'IT', 'Finance'],
    'Salary': [-99999, 80000, np.nan, 55000, -99999,
               90000, 72000, 48000, np.nan, 67000],
    'City': ['  Delhi  ', 'Mumbai', 'Pune', None, 'Bangalore',
             'Mumbai', None, '  Pune  ', 'Bangalore', 'Mumbai'],
    'Experience': [2, 1, 0, np.nan, 1, 5, 8, 3, np.nan, 1]
})
data

  Employee Name   Age Department   Salary       City  Experience
0           Raj  24.0  Marketing -99999.0    Delhi           2.0
1         Ayush   NaN         IT  80000.0     Mumbai         1.0
2       Anamika  20.0       None      NaN       Pune         0.0
3          Pari  20.0         IT  55000.0       None         NaN
4       Rishabh  19.0         HR -99999.0  Bangalore         1.0
5          Neha  28.0    Finance  90000.0     Mumbai         5.0
6        Vikram   NaN  Marketing  72000.0       None         8.0
7         Sneha  25.0       None  48000.0     Pune           3.0
8         Arjun  27.0         IT      NaN  Bangalore         NaN
9         Priya  22.0    Finance  67000.0     Mumbai         1.0

In [72]:
data = data.replace(-99999,np.nan)
data

  Employee Name   Age Department   Salary       City  Experience
0           Raj  24.0  Marketing      NaN    Delhi           2.0
1         Ayush   NaN         IT  80000.0     Mumbai         1.0
2       Anamika  20.0       None      NaN       Pune         0.0
3          Pari  20.0         IT  55000.0       None         NaN
4       Rishabh  19.0         HR      NaN  Bangalore         1.0
5          Neha  28.0    Finance  90000.0     Mumbai         5.0
6        Vikram   NaN  Marketing  72000.0       None         8.0
7         Sneha  25.0       None  48000.0     Pune           3.0
8         Arjun  27.0         IT      NaN  Bangalore         NaN
9         Priya  22.0    Finance  67000.0     Mumbai         1.0

Q2. Convert the values in the Employee Name column to lowercase using str.lower()

In [73]:
data['Employee Name'] = data['Employee Name'].str.lower()
data

  Employee Name   Age Department   Salary       City  Experience
0           raj  24.0  Marketing      NaN    Delhi           2.0
1         ayush   NaN         IT  80000.0     Mumbai         1.0
2       anamika  20.0       None      NaN       Pune         0.0
3          pari  20.0         IT  55000.0       None         NaN
4       rishabh  19.0         HR      NaN  Bangalore         1.0
5          neha  28.0    Finance  90000.0     Mumbai         5.0
6        vikram   NaN  Marketing  72000.0       None         8.0
7         sneha  25.0       None  48000.0     Pune           3.0
8         arjun  27.0         IT      NaN  Bangalore         NaN
9         priya  22.0    Finance  67000.0     Mumbai         1.0

Q3. Remove leading and trailing spaces from the City column using str.strip(). (First, manually add extra spaces to a few values).

In [74]:
data['City'] = data['City'].str.strip()
data

  Employee Name   Age Department   Salary       City  Experience
0           raj  24.0  Marketing      NaN      Delhi         2.0
1         ayush   NaN         IT  80000.0     Mumbai         1.0
2       anamika  20.0       None      NaN       Pune         0.0
3          pari  20.0         IT  55000.0       None         NaN
4       rishabh  19.0         HR      NaN  Bangalore         1.0
5          neha  28.0    Finance  90000.0     Mumbai         5.0
6        vikram   NaN  Marketing  72000.0       None         8.0
7         sneha  25.0       None  48000.0       Pune         3.0
8         arjun  27.0         IT      NaN  Bangalore         NaN
9         priya  22.0    Finance  67000.0     Mumbai         1.0

Q4. Find duplicate rows using duplicated().

In [75]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

Q5. Remove duplicate rows using drop_duplicates().

In [76]:
data.drop_duplicates()

  Employee Name   Age Department   Salary       City  Experience
0           raj  24.0  Marketing      NaN      Delhi         2.0
1         ayush   NaN         IT  80000.0     Mumbai         1.0
2       anamika  20.0       None      NaN       Pune         0.0
3          pari  20.0         IT  55000.0       None         NaN
4       rishabh  19.0         HR      NaN  Bangalore         1.0
5          neha  28.0    Finance  90000.0     Mumbai         5.0
6        vikram   NaN  Marketing  72000.0       None         8.0
7         sneha  25.0       None  48000.0       Pune         3.0
8         arjun  27.0         IT      NaN  Bangalore         NaN
9         priya  22.0    Finance  67000.0     Mumbai         1.0

Q6. Convert all values in the Department column to uppercase using str.upper().

In [77]:
data['Department'] = data['Department'].str.upper()
data

  Employee Name   Age Department   Salary       City  Experience
0           raj  24.0  MARKETING      NaN      Delhi         2.0
1         ayush   NaN         IT  80000.0     Mumbai         1.0
2       anamika  20.0       None      NaN       Pune         0.0
3          pari  20.0         IT  55000.0       None         NaN
4       rishabh  19.0         HR      NaN  Bangalore         1.0
5          neha  28.0    FINANCE  90000.0     Mumbai         5.0
6        vikram   NaN  MARKETING  72000.0       None         8.0
7         sneha  25.0       None  48000.0       Pune         3.0
8         arjun  27.0         IT      NaN  Bangalore         NaN
9         priya  22.0    FINANCE  67000.0     Mumbai         1.0

Q7. Convert the Salary column from string to numeric — first manually convert a few values to strings using astype(str), and then convert them back to numeric using pd.to_numeric()

In [78]:
data['Salary'] = data['Salary'].astype(str)

In [79]:
data['Salary'] = pd.to_numeric(data['Salary'],errors='coerce')
data

  Employee Name   Age Department   Salary       City  Experience
0           raj  24.0  MARKETING      NaN      Delhi         2.0
1         ayush   NaN         IT  80000.0     Mumbai         1.0
2       anamika  20.0       None      NaN       Pune         0.0
3          pari  20.0         IT  55000.0       None         NaN
4       rishabh  19.0         HR      NaN  Bangalore         1.0
5          neha  28.0    FINANCE  90000.0     Mumbai         5.0
6        vikram   NaN  MARKETING  72000.0       None         8.0
7         sneha  25.0       None  48000.0       Pune         3.0
8         arjun  27.0         IT      NaN  Bangalore         NaN
9         priya  22.0    FINANCE  67000.0     Mumbai         1.0