Q1. Create DataFrame from Dictionary
Create a DataFrame from a dictionary containing the following columns for 5 employees: Employee Name, Age, Department, and Salary.

In [27]:
import pandas as pd
data = pd.DataFrame({
    'Employee Name' : ['Raj','Ayush','Anamika','Pari','Rishabh'],
    'Age' : [24,23,20,20,19],
    'Department' : ['Marketing','IT','IT','IT','HR'],
    'Salary' : [35000,80000,75000,55000,60000]
})

Q2. Display First & Last Rows
Display the first 5 rows and the last 5 rows of the DataFrame

In [28]:
data.head()

  Employee Name  Age Department  Salary
0           Raj   24  Marketing   35000
1         Ayush   23         IT   80000
2       Anamika   20         IT   75000
3          Pari   20         IT   55000
4       Rishabh   19         HR   60000

In [29]:
data.tail()

  Employee Name  Age Department  Salary
0           Raj   24  Marketing   35000
1         Ayush   23         IT   80000
2       Anamika   20         IT   75000
3          Pari   20         IT   55000
4       Rishabh   19         HR   60000

Q3. Get Dimension Counts
Display the total count of rows and columns present in the DataFrame.

In [30]:
data.shape

(5, 4)

Q4. List Column Names
Print all column names of the DataFrame

In [31]:
data.columns

Index(['Employee Name', 'Age', 'Department', 'Salary'], dtype='object')

Q5. Select Single Column
Select and display only the Salary column.

In [32]:
data[['Salary']]

   Salary
0   35000
1   80000
2   75000
3   55000
4   60000

Q6. Select Multiple Columns
Select and display both the Age and Department columns together.

In [33]:
data[['Age','Department']]

   Age Department
0   24  Marketing
1   23         IT
2   20         IT
3   20         IT
4   19         HR

Q7. Inspect Structural Attributes
Run shape, columns, dtypes, and info() one by one on your DataFrame to inspect its structural metadata.

In [34]:
data.shape

(5, 4)

In [35]:
data.columns

Index(['Employee Name', 'Age', 'Department', 'Salary'], dtype='object')

In [36]:
data.dtypes

Employee Name    object
Age               int64
Department       object
Salary            int64
dtype: object

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee Name  5 non-null      object
 1   Age            5 non-null      int64
 2   Department     5 non-null      object
 3   Salary         5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes