Day 8 — GroupBy & Aggregation Practice

Q1. Calculate the average salary for each department.

Q2. Find the maximum salary for each department.

Q3. Find the minimum salary for each department.

Q4. Count the number of employees in each department.

Q5. Calculate the average age for each city.

Q6. Group by Department and City and calculate the total salary.

Q7. Use agg() in a single call to calculate the mean, minimum, maximum, and count of Salary for each department.

Q8. Find the department with the highest average salary. Use groupby() + idxmax().

Q9. Find all departments where the total salary exceeds 150,000.

Q10. Group by Department and City and calculate the mean age and mean salary together using agg().

In [1]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika', 'Pari', 'Rishabh',
                      'Neha', 'Vikram', 'Sneha', 'Arjun', 'Priya'],
    'Age': [24, 23, 20, 20, 19, 28, 32, 25, 27, 22],
    'Department': ['Marketing', 'IT', 'IT', 'IT', 'HR',
                   'Finance', 'Marketing', 'HR', 'IT', 'Finance'],
    'Salary': [35000, 80000, 75000, 55000, 60000,
               90000, 72000, 48000, 85000, 67000],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Bangalore',
             'Mumbai', 'Delhi', 'Pune', 'Bangalore', 'Mumbai'],
    'Experience': [2, 1, 0, 0, 1, 5, 8, 3, 4, 1]
})

Q1. Calculate the average salary for each department.

In [4]:
data.groupby('Department')['Salary'].mean()

Department
Finance      78500.0
HR           54000.0
IT           73750.0
Marketing    53500.0
Name: Salary, dtype: float64

Q2. Find the maximum salary for each department.

In [5]:
data.groupby('Department')['Salary'].max()

Department
Finance      90000
HR           60000
IT           85000
Marketing    72000
Name: Salary, dtype: int64

Q3. Find the minimum salary for each department.

In [6]:
data.groupby('Department')['Salary'].min()

Department
Finance      67000
HR           48000
IT           55000
Marketing    35000
Name: Salary, dtype: int64

Q4. Count the number of employees in each department.

In [8]:
data.groupby('Department')['Employee Name'].count()

Department
Finance      2
HR           2
IT           4
Marketing    2
Name: Employee Name, dtype: int64

Q5. Calculate the average age for each city.

In [9]:
data.groupby('City')['Age'].mean()

City
Bangalore    23.000000
Delhi        25.333333
Mumbai       24.333333
Pune         22.500000
Name: Age, dtype: float64

Q6. Group by Department and City and calculate the total salary.

In [14]:
data.groupby(['Department','City'])['Salary'].sum()

Department  City
Finance     Mumbai       157000
HR          Bangalore     60000
            Pune          48000
IT          Bangalore     85000
            Delhi         55000
            Mumbai        80000
            Pune          75000
Marketing   Delhi        107000
Name: Salary, dtype: int64

Q7. Use agg() in a single call to calculate the mean, minimum, maximum, and count of Salary for each department.

In [19]:
data.groupby('Department')['Salary'].agg(['mean', 'min', 'max', 'count'])

               mean    min    max  count
Department
Finance     78500.0  67000  90000      2
HR          54000.0  48000  60000      2
IT          73750.0  55000  85000      4
Marketing   53500.0  35000  72000      2

Q8. Find the department with the highest average salary (use groupby + idxmax()).

In [24]:
data.groupby('Department')['Salary'].mean().idxmax()

'Finance'

Q9. Find all departments where total salary exceeds 150,000.

In [30]:
result = data.groupby('Department')['Salary'].sum()
result[result > 150000]

Department
Finance    157000
IT         295000
Name: Salary, dtype: int64

Q10. Group by two columns (Department and City) and calculate mean age and mean salary together using agg().

In [36]:
data.groupby(['Department','City'])[['Age','Salary']].agg('mean')

                       Age   Salary
Department City
Finance    Mumbai     25.0  78500.0
HR         Bangalore  19.0  60000.0
           Pune       25.0  48000.0
IT         Bangalore  27.0  85000.0
           Delhi      20.0  55000.0
           Mumbai     23.0  80000.0
           Pune       20.0  75000.0
Marketing  Delhi      28.0  53500.0