In [28]:
import pandas as pd
import numpy as np
products = pd.DataFrame({
    'product_id': [1, 2, 3, 4, 5],
    'product_name': ['Laptop', 'Phone', 'Tablet', 'Watch', 'Earbuds'],
    'category': ['Electronics', 'Electronics', 'Electronics', 'Accessories', 'Accessories'],
    'price': [50000, 30000, 25000, 8000, 3000]
})

sales = pd.DataFrame({
    'sale_id': [101, 102, 103, 104, 105, 106],
    'product_id': [1, 2, 1, 6, 3, 2],
    'quantity': [2, 1, 3, 1, 2, 4],
    'city': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune']
})

Q1.Perform an inner join between products and sales on product_id to display only the products that have sales.

In [14]:
df = pd.merge(products,sales,on="product_id",how="inner")
df

   product_id product_name     category  price  sale_id  quantity    city
0           1       Laptop  Electronics  50000      101         2   Delhi
1           1       Laptop  Electronics  50000      103         3    Pune
2           2        Phone  Electronics  30000      102         1  Mumbai
3           2        Phone  Electronics  30000      106         4    Pune
4           3       Tablet  Electronics  25000      105         2  Mumbai

Q2.Perform a left join between products and sales, then find the products that have no sales by filtering rows where sale_id is missing.

In [19]:
df = pd.merge(products,sales,on="product_id",how='left')
df[df['sale_id'].isna()]

   product_id product_name     category  price  sale_id  quantity city
5           4        Watch  Accessories   8000      NaN       NaN  NaN
6           5      Earbuds  Accessories   3000      NaN       NaN  NaN

Q3.Perform a left join and return only the product_name of products that have no sales.

In [ ]:
df = pd.merge(products,sales,on="product_id",how='left')
df[df['sale_id'].isna()]['product_name']

  product_name
5        Watch
6      Earbuds

Q4.Perform an outer join between products and sales using indicator=True, then return only the rows where _merge is right_only.

In [22]:
df = pd.merge(products,sales,on='product_id',how='outer',indicator=True)
df[df['_merge'] == 'right_only']

,product_id,product_name,category,price,sale_id,quantity,city,_merge
7,6,NaN,NaN,NaN,104.0,1.0,Delhi,right_only

Q5.Perform an inner join between products and sales, then filter rows where price is between 10,000 and 40,000 (inclusive). Use & to combine the conditions

In [26]:
df = pd.merge(products,sales,on='product_id',how='inner')
df[(df['price'] >= 10000) & (df['price'] <= 40000)]

   product_id product_name     category  price  sale_id  quantity    city
2           2        Phone  Electronics  30000      102         1  Mumbai
3           2        Phone  Electronics  30000      106         4    Pune
4           3       Tablet  Electronics  25000      105         2  Mumbai

Q6.Perform an inner join between products and sales, then calculate the average price for each category.

In [31]:
df = pd.merge(products,sales,on='product_id',how='inner')
df.groupby('category')['price'].mean()

category
Electronics    37000.0
Name: price, dtype: float64

Q7.Perform an inner join between products and sales, then calculate the total quantity for each city and sort the result in descending order.

In [35]:
df = pd.merge(products,sales,on='product_id',how='inner')
df.groupby('city')['quantity'].sum().sort_values(ascending=False)

city
Pune      7
Mumbai    3
Delhi     2
Name: quantity, dtype: int64

Q8.Perform a left join between products and sales, drop rows where sale_id is missing using dropna(), and count the remaining rows.

In [47]:
df = pd.merge(products,sales,on='product_id',how='left')
sold_product = df.dropna(subset=['sale_id'])
len(sold_product)

5

Q9.Perform an inner join between products and sales, group by product_id, calculate the total quantity, filter totals greater than 2, and sort the result in ascending order.

In [50]:
df = pd.merge(products,sales,on='product_id',how='inner')
total_quantity = df.groupby('product_id')['quantity'].sum()
total_quantity[total_quantity > 2].sort_values(ascending=True)

product_id
1    5
2    5
Name: quantity, dtype: int64

Q10.Perform an inner join between products and sales, group by category, calculate the average price, filter averages greater than 15,000, and sort the result in descending order.

In [54]:
df = pd.merge(products,sales,on='product_id',how='inner')
avg_price = df.groupby('category')['price'].mean()
avg_price[avg_price > 15000].sort_values(ascending=False)

category
Electronics    37000.0
Name: price, dtype: float64