In [8]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika'],
    'Department': ['Marketing', 'IT', 'IT'],
    'Salary': [35000, 80000, 75000]
})

df2 = pd.DataFrame({
    'Employee Name': ['Pari', 'Rishabh', 'Neha'],
    'Department': ['IT', 'HR', 'Finance'],
    'Salary': [55000, 60000, 90000]
})

customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Raj', 'Ayush', 'Pari', 'Neha']
})

orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104],
    'customer_id': [1, 2, 5, 3],
    'amount': [500, 300, 700, 200]
})

**Q1.** Concatenate `df1` and `df2` vertically (append rows).

In [9]:
pd.concat([df1,df2])

  Employee Name Department  Salary
0           Raj  Marketing   35000
1         Ayush         IT   80000
2       Anamika         IT   75000
0          Pari         IT   55000
1       Rishabh         HR   60000
2          Neha    Finance   90000

**Q2.** Concatenate `df1` and `df2` vertically and reset the index.

In [11]:
pd.concat([df1,df2]).reset_index()

   index Employee Name Department  Salary
0      0           Raj  Marketing   35000
1      1         Ayush         IT   80000
2      2       Anamika         IT   75000
3      0          Pari         IT   55000
4      1       Rishabh         HR   60000
5      2          Neha    Finance   90000

**Q3.** Concatenate `df1` and `df2` horizontally (side by side).

In [14]:
pd.concat([df1,df2], axis=1)

  Employee Name Department  Salary Employee Name Department  Salary
0           Raj  Marketing   35000          Pari         IT   55000
1         Ayush         IT   80000       Rishabh         HR   60000
2       Anamika         IT   75000          Neha    Finance   90000

**Q4.** Perform an inner join between `customers` and `orders` using `customer_id`.

In [16]:
pd.merge(customers,orders,on='customer_id',how='inner')

   customer_id   name  order_id  amount
0            1    Raj       101     500
1            2  Ayush       102     300
2            3   Pari       104     200

**Q5.** Perform a left join so that customers who have no orders are also included.

In [19]:
pd.merge(customers,orders,on='customer_id',how='left')

   customer_id   name  order_id  amount
0            1    Raj     101.0   500.0
1            2  Ayush     102.0   300.0
2            3   Pari     104.0   200.0
3            4   Neha       NaN     NaN

**Q6.** Perform a right join between `customers` and `orders`.

In [21]:
pd.merge(customers,orders,on='customer_id',how='right')

   customer_id   name  order_id  amount
0            1    Raj       101     500
1            2  Ayush       102     300
2            5    NaN       103     700
3            3   Pari       104     200

**Q7.** Perform an outer join between `customers` and `orders` and use `indicator=True`.

In [27]:
pd.merge(orders,customers,on='customer_id',how='outer',indicator=True)

   order_id  customer_id  amount   name      _merge
0     101.0            1   500.0    Raj        both
1     102.0            2   300.0  Ayush        both
2     104.0            3   200.0   Pari        both
3       NaN            4     NaN   Neha  right_only
4     103.0            5   700.0    NaN   left_only

**Q8.** Concatenate `df1` and `df2` using `keys=['batch1', 'batch2']`, then extract the `batch1` data using `.loc`.

In [29]:
result = pd.concat([df1,df2], keys=['batch1','batch2'])
result.loc['batch1']

  Employee Name Department  Salary
0           Raj  Marketing   35000
1         Ayush         IT   80000
2       Anamika         IT   75000

**Q9.** Merge two DataFrames where the join column names are different. Use `left_on` and `right_on`.

In [ ]:
pd.merge(customers, orders,
         left_on='customer_id',
         right_on='cust_id')

**Q10.** After merging `customers` and `orders`, calculate the total order amount for each customer.

In [44]:
total_or_amo = pd.merge(customers,orders)
total_or_amo.groupby('customer_id')['amount'].sum()

customer_id
1    500
2    300
3    200
Name: amount, dtype: int64