Day 11 — Pandas Practice Questions
1. Concatenate df1 and df2, then filter only the rows where the Department is IT.
2. Perform an inner join between customers and orders using customer_id, then filter the rows where amount is greater than 400.
3. Perform a left join between customers and orders, then identify the customers who do not have any orders by filtering rows where order_id is NaN.
4. Perform an outer join between customers and orders using customer_id with indicator=True, then filter only the rows where _merge is left_only.
5. Merge customers and orders, calculate the total order amount for each customer, and sort the result in descending order.
6. Concatenate df1 and df2 using keys=['team1', 'team2'], then extract the team2 data using .loc.
7. Concatenate df1 and df2, then calculate the average salary for each department.
8. Merge customers and orders, then keep only the name column from customers and the amount column from orders in the final result.
9. Horizontally concatenate df1 and df2. First predict how many columns the resulting DataFrame will have, then run the code and verify your answer.
10. Merge customers and orders, calculate the total order amount for each customer, and then filter only the customers whose total amount is greater than 400.

Recall Day 11
1. pd.concat([df1, df2])
2. pd.concat([df1, df2]).reset_index(drop=True)
3. pd.merge(df1, df2, on='col', how='left')
4. pd.merge(df1, df2, on='col', how='outer', indicator=True)
5. pd.merge(df1, df2, on='col').groupby('col2')['col3'].sum()

In [1]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika'],
    'Department': ['Marketing', 'IT', 'IT'],
    'Salary': [35000, 80000, 75000]
})

df2 = pd.DataFrame({
    'Employee Name': ['Pari', 'Rishabh', 'Neha'],
    'Department': ['IT', 'HR', 'Finance'],
    'Salary': [55000, 60000, 90000]
})

customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Raj', 'Ayush', 'Pari', 'Neha']
})

orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104],
    'customer_id': [1, 2, 5, 3],
    'amount': [500, 300, 700, 200]
})

1 .Concatenate df1 and df2, then filter only the rows where the Department is IT.

In [7]:
result = pd.concat([df1,df2])
result[result['Department'] == 'IT']

  Employee Name Department  Salary
1         Ayush         IT   80000
2       Anamika         IT   75000
0          Pari         IT   55000

2. Perform an inner join between customers and orders using customer_id, then filter the rows where amount is greater than 400.

In [21]:
result = pd.merge(customers,orders,on='customer_id',how='inner')
result[ result['amount'] > 400 ]

   customer_id name  order_id  amount
0            1  Raj       101     500

Q3. Perform a left join, then identify which customers do not have any orders (rows where order information is NaN).

In [ ]:
result = pd.merge(customers,orders,on='customer_id',how='left')
result[result['order_id'].isna()]

   customer_id  name  order_id  amount
3            4  Neha       NaN     NaN

Q4. Perform an outer join with indicator=True, then return only the rows where _merge == 'left_only'

In [37]:
result  = pd.merge(customers,orders,on='customer_id',how='outer',indicator=True)
result[result['_merge'] == 'left_only']

   customer_id  name  order_id  amount     _merge
3            4  Neha       NaN     NaN  left_only

Q5. Merge customers and orders, then calculate the total order amount for each customer, and finally sort the result in descending order.

In [51]:
result = pd.merge(customers,orders,on='customer_id',how='outer')
result.groupby('customer_id')['amount'].sum().sort_values(ascending=False)

customer_id
5    700.0
1    500.0
2    300.0
3    200.0
4      0.0
Name: amount, dtype: float64

Q6. Concatenate df1 and df2 using keys=['team1', 'team2'], then extract the team2 data.

In [57]:
result = pd.concat([df1,df2],keys=['team1', 'team2'])
result.loc['team2']

  Employee Name Department  Salary
0          Pari         IT   55000
1       Rishabh         HR   60000
2          Neha    Finance   90000

7. Concatenate df1 and df2, then calculate the average salary for each department

In [62]:
result =pd.concat([df1,df2], ignore_index=True)
result.groupby('Department')['Salary'].mean()

Department
Finance      90000.0
HR           60000.0
IT           70000.0
Marketing    35000.0
Name: Salary, dtype: float64

Q8. Merge customers and orders, then keep only the name column from customers and the amount column from orders in the final result.

In [66]:
result = pd.merge(customers,orders,on='customer_id',how='outer')
result[['name','amount']]

    name  amount
0    Raj   500.0
1  Ayush   300.0
2   Pari   200.0
3   Neha     NaN
4    NaN   700.0

Q9. Horizontally concatenate df1 and df2. First predict how many columns the resulting DataFrame will have, then run the code and verify your answer.

In [76]:
pd.concat([df1,df2],axis=1)

  Employee Name Department  Salary Employee Name Department  Salary
0           Raj  Marketing   35000          Pari         IT   55000
1         Ayush         IT   80000       Rishabh         HR   60000
2       Anamika         IT   75000          Neha    Finance   90000

Q10. Merge customers and orders, calculate the total amount for each customer, and then filter only the customers whose total amount is greater than 400.

In [82]:
result = pd.merge(customers,orders,on='customer_id',how='outer')
total_amt = result.groupby('customer_id')['amount'].sum()
total_amt[total_amt > 400]

customer_id
1    500.0
5    700.0
Name: amount, dtype: float64