Q1. Select rows 3 to 6 and only the Employee Name, Department, and Salary columns using .loc.

Q2. Select the first 4 rows and the first 3 columns using .iloc.

Q3. Set the Experience column as the DataFrame index, and then reset it back to default.

Q4. Sort the DataFrame by its index using sort_index().

Q5. Extract rows where the City column contains the word 'Mumbai' using str.contains().

Q6. Select the first 10 rows using .loc (all 10 rows should be visible as the DataFrame contains 10 rows).

In [1]:
import pandas as pd
data = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika', 'Pari', 'Rishabh', 
                      'Neha', 'Vikram', 'Sneha', 'Arjun', 'Priya'],
    'Age': [24, 23, 20, 20, 19, 28, 32, 25, 27, 22],
    'Department': ['Marketing', 'IT', 'IT', 'IT', 'HR', 
                   'Finance', 'Marketing', 'HR', 'IT', 'Finance'],
    'Salary': [35000, 80000, 75000, 55000, 60000, 
               90000, 72000, 48000, 85000, 67000],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Bangalore',
             'Mumbai', 'Delhi', 'Pune', 'Bangalore', 'Mumbai'],
    'Experience': [2, 1, 0, 0, 1, 5, 8, 3, 4, 1]
})
data

  Employee Name  Age Department  Salary       City  Experience
0           Raj   24  Marketing   35000      Delhi           2
1         Ayush   23         IT   80000     Mumbai           1
2       Anamika   20         IT   75000       Pune           0
3          Pari   20         IT   55000      Delhi           0
4       Rishabh   19         HR   60000  Bangalore           1
5          Neha   28    Finance   90000     Mumbai           5
6        Vikram   32  Marketing   72000      Delhi           8
7         Sneha   25         HR   48000       Pune           3
8         Arjun   27         IT   85000  Bangalore           4
9         Priya   22    Finance   67000     Mumbai           1

Q1. Select rows 3 to 6 and only the Employee Name, Department, and Salary columns using .loc.

In [2]:
data.loc[3:6,['Employee Name','Department',"Salary"]]

  Employee Name Department  Salary
3          Pari         IT   55000
4       Rishabh         HR   60000
5          Neha    Finance   90000
6        Vikram  Marketing   72000

Q2. Select the first 4 rows and the first 3 columns using .iloc.

In [3]:

data.iloc[0:4,0:3]

  Employee Name  Age Department
0           Raj   24  Marketing
1         Ayush   23         IT
2       Anamika   20         IT
3          Pari   20         IT

Q3. Set the Experience column as the DataFrame index, and then reset it back to default.

In [4]:
data = data.set_index('Experience')
data

           Employee Name  Age Department  Salary       City
Experience
2                    Raj   24  Marketing   35000      Delhi
1                  Ayush   23         IT   80000     Mumbai
0                Anamika   20         IT   75000       Pune
0                   Pari   20         IT   55000      Delhi
1                Rishabh   19         HR   60000  Bangalore
5                   Neha   28    Finance   90000     Mumbai
8                 Vikram   32  Marketing   72000      Delhi
3                  Sneha   25         HR   48000       Pune
4                  Arjun   27         IT   85000  Bangalore
1                  Priya   22    Finance   67000     Mumbai

In [5]:
data = data.reset_index(drop=True)
data

  Employee Name  Age Department  Salary       City
0           Raj   24  Marketing   35000      Delhi
1         Ayush   23         IT   80000     Mumbai
2       Anamika   20         IT   75000       Pune
3          Pari   20         IT   55000      Delhi
4       Rishabh   19         HR   60000  Bangalore
5          Neha   28    Finance   90000     Mumbai
6        Vikram   32  Marketing   72000      Delhi
7         Sneha   25         HR   48000       Pune
8         Arjun   27         IT   85000  Bangalore
9         Priya   22    Finance   67000     Mumbai

Q4. Sort the DataFrame by its index using sort_index().

In [6]:
data.sort_index()

  Employee Name  Age Department  Salary       City
0           Raj   24  Marketing   35000      Delhi
1         Ayush   23         IT   80000     Mumbai
2       Anamika   20         IT   75000       Pune
3          Pari   20         IT   55000      Delhi
4       Rishabh   19         HR   60000  Bangalore
5          Neha   28    Finance   90000     Mumbai
6        Vikram   32  Marketing   72000      Delhi
7         Sneha   25         HR   48000       Pune
8         Arjun   27         IT   85000  Bangalore
9         Priya   22    Finance   67000     Mumbai

Q5. Extract rows where the City column contains the word 'Mumbai' using str.contains().

In [14]:
data[data['City'].str.contains('Mumbai', case=False)]

  Employee Name  Age Department  Salary    City
1         Ayush   23         IT   80000  Mumbai
5          Neha   28    Finance   90000  Mumbai
9         Priya   22    Finance   67000  Mumbai

Q6. Select the first 10 rows using .loc (all 10 rows should be visible as the DataFrame contains 10 rows).

In [12]:
data.loc[:]

  Employee Name  Age Department  Salary       City
0           Raj   24  Marketing   35000      Delhi
1         Ayush   23         IT   80000     Mumbai
2       Anamika   20         IT   75000       Pune
3          Pari   20         IT   55000      Delhi
4       Rishabh   19         HR   60000  Bangalore
5          Neha   28    Finance   90000     Mumbai
6        Vikram   32  Marketing   72000      Delhi
7         Sneha   25         HR   48000       Pune
8         Arjun   27         IT   85000  Bangalore
9         Priya   22    Finance   67000     Mumbai