In [1]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika'],
    'Department': ['Marketing', 'IT', 'IT'],
    'Salary': [35000, 80000, 75000]
})

df2 = pd.DataFrame({
    'Employee Name': ['Pari', 'Rishabh', 'Neha'],
    'Department': ['IT', 'HR', 'Finance'],
    'Salary': [55000, 60000, 90000]
})

customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Raj', 'Ayush', 'Pari', 'Neha']
})

orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104],
    'customer_id': [1, 2, 5, 3],
    'amount': [500, 300, 700, 200]
})

Q1. Concatenate df1 and df2, then filter the rows where Salary is greater than 60000.

In [16]:
result = pd.concat([df1,df2])
result[result['Salary'] > 60000]

  Employee Name Department  Salary
1         Ayush         IT   80000
2       Anamika         IT   75000
2          Neha    Finance   90000

Q2. Perform an inner join between customers and orders, then calculate the total sum of amount as a single number.

In [18]:
result = pd.merge(customers,orders,on='customer_id', how='inner')
result['amount'].sum()

np.int64(1000)

Q3. Perform a left join between customers and orders, then return the name of customers who do not have any orders.

In [23]:
result = pd.merge(customers,orders,on='customer_id', how='left')
result[result['order_id'].isna()]['name']

3    Neha
Name: name, dtype: object

Q4: Perform an outer join between customers and orders with indicator=True, then return only the rows where _merge == 'right_only'.

In [25]:
result = pd.merge(customers,orders,on='customer_id', how='outer',indicator=True)
result[result['_merge'] == 'right_only']

   customer_id name  order_id  amount      _merge
4            5  NaN     103.0   700.0  right_only

Q5.Merge customers and orders, calculate the average amount for each customer, and sort the result in descending order.

In [31]:
result = pd.merge(customers,orders,on='customer_id', how='outer')
result.groupby('customer_id')['amount'].mean().sort_values(ascending=False)

customer_id
5    700.0
1    500.0
2    300.0
3    200.0
4      NaN
Name: amount, dtype: float64

Q6. Concatenate df1 and df2 using keys=['batch1', 'batch2'], then count the rows in batch1.

In [14]:
result = pd.concat([df1,df2],keys=['batch1','batch2'])
result.loc['batch1'].shape[0]

3

Q7. Concatenate df1 and df2, then calculate the maximum salary for each department.

In [19]:
result = pd.concat([df1,df2])
result.groupby('Department')['Salary'].max()

Department
Finance      90000
HR           60000
IT           80000
Marketing    35000
Name: Salary, dtype: int64

Q8.Merge customers and orders, then filter the rows where amount is between 300 and 600 (use &).

In [33]:
result = pd.merge(customers,orders,on='customer_id',how='outer')
result[(result['amount'] >= 300) & (result['amount'] <= 600)]

   customer_id   name  order_id  amount
0            1    Raj     101.0   500.0
1            2  Ayush     102.0   300.0

Q9. perform a left join between customers and orders, remove rows with missing order_id, and find how many rows are left.

In [46]:
result = pd.merge(customers,orders,on='customer_id',how='left')
result.dropna(subset=['order_id'],inplace=True)
len(result)

3

Q10.Merge → groupby name → calculate total amount → keep totals greater than 400 → sort the result in ascending order.

In [48]:
result =pd.merge(customers,orders,on='customer_id',how='outer')
total_amt = result.groupby('name')['amount'].sum()
total_amt[total_amt > 400].sort_values(ascending=True)

name
Raj    500.0
Name: amount, dtype: float64