Q1. Rename three columns in a single call — Employee Name → Name, Salary → Monthly_Salary, Experience → Exp_Years.
Q2. Convert all column names to lowercase.
Q3. Replace 'IT' with 'Information Technology' in the Department column.
Q4. Replace 'Delhi' with 'New Delhi' and 'Pune' with 'Pune City' in the City column — both in a single replace() call.
Q5. Create a clean copy of the DataFrame without changing the original (copy()).
Q6. Replace values in the Salary column: values below 50000 with 'Low', 50000–75000 with 'Medium', and values above 75000 with 'High' (use pd.cut()).
Q7. Check the dtype of the Age column, then convert it to float.

In [72]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika', 'Pari', 'Rishabh',
                      'Neha', 'Vikram', 'Sneha', 'Arjun', 'Priya'],
    'Age': [24, 23, 20, 20, 19, 28, 32, 25, 27, 22],
    'Department': ['Marketing', 'IT', 'IT', 'IT', 'HR',
                   'Finance', 'Marketing', 'HR', 'IT', 'Finance'],
    'Salary': [35000, 80000, 75000, 55000, 60000,
               90000, 72000, 48000, 85000, 67000],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Bangalore',
             'Mumbai', 'Delhi', 'Pune', 'Bangalore', 'Mumbai'],
    'Experience': [2, 1, 0, 0, 1, 5, 8, 3, 4, 1]
})

Q1. Rename three columns in a single call — Employee Name → Name, Salary → Monthly_Salary, Experience → Exp_Years.

In [73]:
data.rename(columns={
    'Employee Name' : 'Name',
    'Salary' : 'Monthly_Salary',
    'Experience' : 'Exp_Years'
}, inplace=True)
data

      Name  Age Department  Monthly_Salary       City  Exp_Years
0      Raj   24  Marketing           35000      Delhi          2
1    Ayush   23         IT           80000     Mumbai          1
2  Anamika   20         IT           75000       Pune          0
3     Pari   20         IT           55000      Delhi          0
4  Rishabh   19         HR           60000  Bangalore          1
5     Neha   28    Finance           90000     Mumbai          5
6   Vikram   32  Marketing           72000      Delhi          8
7    Sneha   25         HR           48000       Pune          3
8    Arjun   27         IT           85000  Bangalore          4
9    Priya   22    Finance           67000     Mumbai          1

Q2. Convert all column names to lowercase.

In [74]:
data.columns = data.columns.str.lower()
data

      name  age department  monthly_salary       city  exp_years
0      Raj   24  Marketing           35000      Delhi          2
1    Ayush   23         IT           80000     Mumbai          1
2  Anamika   20         IT           75000       Pune          0
3     Pari   20         IT           55000      Delhi          0
4  Rishabh   19         HR           60000  Bangalore          1
5     Neha   28    Finance           90000     Mumbai          5
6   Vikram   32  Marketing           72000      Delhi          8
7    Sneha   25         HR           48000       Pune          3
8    Arjun   27         IT           85000  Bangalore          4
9    Priya   22    Finance           67000     Mumbai          1

Q3. Replace 'IT' with 'Information Technology' in the Department column.

In [75]:
data['department'] = data['department'].replace('IT','Information Technology')
data

      name  age              department  monthly_salary       city  exp_years
0      Raj   24               Marketing           35000      Delhi          2
1    Ayush   23  Information Technology           80000     Mumbai          1
2  Anamika   20  Information Technology           75000       Pune          0
3     Pari   20  Information Technology           55000      Delhi          0
4  Rishabh   19                      HR           60000  Bangalore          1
5     Neha   28                 Finance           90000     Mumbai          5
6   Vikram   32               Marketing           72000      Delhi          8
7    Sneha   25                      HR           48000       Pune          3
8    Arjun   27  Information Technology           85000  Bangalore          4
9    Priya   22                 Finance           67000     Mumbai          1

Q4. Replace 'Delhi' with 'New Delhi' and 'Pune' with 'Pune City' in the City column — both in a single replace() call.

In [76]:
data['city'].replace({
    'Delhi': 'New Delhi',
    'Pune': 'Pune City'
}, inplace=True)

C:\Users\ap504\AppData\Local\Temp\ipykernel_31644\2892266537.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['city'].replace({

Q5. Create a clean copy of the DataFrame without changing the original (copy()).

In [77]:
copied_data = data.copy()
copied_data

      name  age              department  monthly_salary       city  exp_years
0      Raj   24               Marketing           35000  New Delhi          2
1    Ayush   23  Information Technology           80000     Mumbai          1
2  Anamika   20  Information Technology           75000  Pune City          0
3     Pari   20  Information Technology           55000  New Delhi          0
4  Rishabh   19                      HR           60000  Bangalore          1
5     Neha   28                 Finance           90000     Mumbai          5
6   Vikram   32               Marketing           72000  New Delhi          8
7    Sneha   25                      HR           48000  Pune City          3
8    Arjun   27  Information Technology           85000  Bangalore          4
9    Priya   22                 Finance           67000     Mumbai          1

Q6. Replace values in the Salary column: values below 50000 with 'Low', 50000–75000 with 'Medium', and values above 75000 with 'High' (use pd.cut()).

In [78]:
data['monthly_salary'] = pd.cut(
    data['monthly_salary'],
    bins=[0,50000,75000,np.inf],
    labels=['Low','Medium','High'],
)
data

      name  age              department monthly_salary       city  exp_years
0      Raj   24               Marketing            Low  New Delhi          2
1    Ayush   23  Information Technology           High     Mumbai          1
2  Anamika   20  Information Technology         Medium  Pune City          0
3     Pari   20  Information Technology         Medium  New Delhi          0
4  Rishabh   19                      HR         Medium  Bangalore          1
5     Neha   28                 Finance           High     Mumbai          5
6   Vikram   32               Marketing         Medium  New Delhi          8
7    Sneha   25                      HR            Low  Pune City          3
8    Arjun   27  Information Technology           High  Bangalore          4
9    Priya   22                 Finance         Medium     Mumbai          1

Q7. Check the dtype of the Age column, then convert it to float.

In [79]:
data['age'].dtype

dtype('int64')

In [81]:
data['age'] = data['age'].astype(float)
data['age'].dtype

dtype('float64')