In [1]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika'],
    'Department': ['Marketing', 'IT', 'IT'],
    'Salary': [35000, 80000, 75000]
})

df2 = pd.DataFrame({
    'Employee Name': ['Pari', 'Rishabh', 'Neha'],
    'Department': ['IT', 'HR', 'Finance'],
    'Salary': [55000, 60000, 90000]
})

customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Raj', 'Ayush', 'Pari', 'Neha']
})

orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104],
    'customer_id': [1, 2, 5, 3],
    'amount': [500, 300, 700, 200]
})

Q1. Perform a left join between customers and orders, then return the name of customers who have no orders.

In [38]:
result = pd.merge(customers,orders,on='customer_id',how='left')
result[result['order_id'].isna()]['name']

3    Neha
Name: name, dtype: object

Q2. Merge customers and orders, calculate the average amount for each customer_id, and sort the result in descending order.

In [39]:
result = pd.merge(customers,orders,on='customer_id',how='outer')
result.groupby("customer_id")['amount'].mean().sort_values(ascending=False)

customer_id
5    700.0
1    500.0
2    300.0
3    200.0
4      NaN
Name: amount, dtype: float64

Q3.Perform a left join, remove rows where order_id is missing using dropna(), and count the remaining rows.

In [43]:
result = pd.merge(customers,orders,on='customer_id',how='left')
result.dropna(subset=['order_id'],inplace=True)
len(result)

3

Q4.Perform an outer join with indicator=True, then return only the rows where _merge is right_only.

In [45]:
result = pd.merge(customers,orders,on='customer_id',how='outer',indicator=True)
result[result['_merge'] == 'right_only']

   customer_id name  order_id  amount      _merge
4            5  NaN     103.0   700.0  right_only

Q5. Merge customers and orders, calculate the average amount for each customer_id, and keep only customers whose average amount is greater than 300.

In [61]:
result = pd.merge(customers,orders,on='customer_id',how='outer')
avg_amount = result.groupby('customer_id')['amount'].mean()
avg_amount[avg_amount > 300]

customer_id
1    500.0
5    700.0
Name: amount, dtype: float64

Q6. Perform a left join and return only the name column for customers whose order_id is missing.

In [ ]:
result = pd.merge(customers,orders,on='customer_id',how='left')
result[result['order_id'].isna()]['name']

3    Neha
Name: name, dtype: object

Q7.Merge customers and orders, calculate the average amount for each customer, and sort the result in ascending order.

In [63]:
result = pd.merge(customers,orders,on='customer_id',how='outer')
result.groupby('customer_id')['amount'].mean().sort_values(ascending=True)

customer_id
3    200.0
2    300.0
1    500.0
5    700.0
4      NaN
Name: amount, dtype: float64

Q8. Perform a left join, remove all rows with missing order_id, and display the final DataFrame.

In [66]:
result = pd.merge(customers,orders,on='customer_id',how='left')
removed_null = result.dropna(subset=['order_id'])
removed_null

   customer_id   name  order_id  amount
0            1    Raj     101.0   500.0
1            2  Ayush     102.0   300.0
2            3   Pari     104.0   200.0

Q9. Perform an outer join with indicator=True, then return only the rows where _merge is left_only.

In [ ]:
result = pd.merge(customers,orders,on='customer_id',how='outer',indicator=True)
result[result['_merge'] == 'left_only']

   customer_id  name  order_id  amount     _merge
3            4  Neha       NaN     NaN  left_only

Q10.Merge customers and orders, calculate the average amount for each customer, filter averages greater than 250, and sort them in descending order.

In [70]:
result = pd.merge(customers,orders,on='customer_id',how='outer')
avg_amt = result.groupby('customer_id')['amount'].mean()
avg_amt[avg_amt > 250].sort_values(ascending=False)

customer_id
5    700.0
1    500.0
2    300.0
Name: amount, dtype: float64