Q1. Backward fill the missing values in the "Department" column.

Q2. Replace the missing values in the "Salary" column with -1 (placeholder value).

Q3. Interpolate the missing values in the "Experience" column.

Q4. Replace -99999 with np.nan — first manually insert a few -99999 values into the DataFrame, then perform the replacement.

Q5. Compare the row counts before and after dropping missing values.

Q6. Keep only those rows that have at least 4 non-null values (dropna(thresh=4)).

Q7. Fill the missing values for both the "City" and "Age" columns simultaneously in a single fillna() call using a dictionary.

In [1]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika', 'Pari', 'Rishabh', 
                      'Neha', 'Vikram', 'Sneha', 'Arjun', 'Priya'],
    'Age': [24, np.nan, 20, 20, 19, 28, np.nan, 25, 27, 22],
    'Department': ['Marketing', 'IT', None, 'IT', 'HR', 
                   'Finance', 'Marketing', None, 'IT', 'Finance'],
    'Salary': [35000, 80000, np.nan, 55000, 60000, 
               90000, 72000, 48000, np.nan, 67000],
    'City': ['Delhi', 'Mumbai', 'Pune', None, 'Bangalore',
             'Mumbai', None, 'Pune', 'Bangalore', 'Mumbai'],
    'Experience': [2, 1, 0, np.nan, 1, 5, 8, 3, np.nan, 1]
})
data

  Employee Name   Age Department   Salary       City  Experience
0           Raj  24.0  Marketing  35000.0      Delhi         2.0
1         Ayush   NaN         IT  80000.0     Mumbai         1.0
2       Anamika  20.0       None      NaN       Pune         0.0
3          Pari  20.0         IT  55000.0       None         NaN
4       Rishabh  19.0         HR  60000.0  Bangalore         1.0
5          Neha  28.0    Finance  90000.0     Mumbai         5.0
6        Vikram   NaN  Marketing  72000.0       None         8.0
7         Sneha  25.0       None  48000.0       Pune         3.0
8         Arjun  27.0         IT      NaN  Bangalore         NaN
9         Priya  22.0    Finance  67000.0     Mumbai         1.0

Q1. Backward fill the missing values in the "Department" column.

In [2]:
data['Department'].bfill()

0    Marketing
1           IT
2           IT
3           IT
4           HR
5      Finance
6    Marketing
7           IT
8           IT
9      Finance
Name: Department, dtype: object

Q2. Replace the missing values in the "Salary" column with -1 (placeholder value).

In [7]:
data['Salary'].fillna(-1)

0    35000.0
1    80000.0
2       -1.0
3    55000.0
4    60000.0
5    90000.0
6    72000.0
7    48000.0
8       -1.0
9    67000.0
Name: Salary, dtype: float64

Q3. Interpolate the missing values in the "Experience" column.

In [8]:
data['Experience'].interpolate()

0    2.0
1    1.0
2    0.0
3    0.5
4    1.0
5    5.0
6    8.0
7    3.0
8    2.0
9    1.0
Name: Experience, dtype: float64

Q4. Replace -99999 with np.nan — first manually insert a few -99999 values into the DataFrame, then perform the replacement.

In [10]:
data = pd.DataFrame({
    'Employee Name': ['Raj', 'Ayush', 'Anamika', 'Pari', 'Rishabh', 
                      'Neha', 'Vikram', 'Sneha', 'Arjun', 'Priya'],
    'Age': [24, np.nan, 20, -99999, 19, 28, np.nan, 25, -99999, 22],
    'Department': ['Marketing', 'IT', None, 'IT', '-99999', 
                   'Finance', '-99999', None, 'IT', 'Finance'],
    'Salary': [-99999, 80000, np.nan, 55000, 60000, 
               90000, -99999, 48000, np.nan, 67000],
    'City': ['Delhi', 'Mumbai', 'Pune', None, 'Bangalore',
             'Mumbai', None, 'Pune', 'Bangalore', 'Mumbai'],
    'Experience': [-99999, 1, 0, np.nan, 1, 5, 8, 3, np.nan, 1]
})

In [11]:
data.replace(-99999,np.nan)

  Employee Name   Age Department   Salary       City  Experience
0           Raj  24.0  Marketing      NaN      Delhi         NaN
1         Ayush   NaN         IT  80000.0     Mumbai         1.0
2       Anamika  20.0       None      NaN       Pune         0.0
3          Pari   NaN         IT  55000.0       None         NaN
4       Rishabh  19.0     -99999  60000.0  Bangalore         1.0
5          Neha  28.0    Finance  90000.0     Mumbai         5.0
6        Vikram   NaN     -99999      NaN       None         8.0
7         Sneha  25.0       None  48000.0       Pune         3.0
8         Arjun   NaN         IT      NaN  Bangalore         NaN
9         Priya  22.0    Finance  67000.0     Mumbai         1.0

Q5. Compare the row counts before and after dropping missing values.

In [13]:
len(data)

10

In [16]:
len(data.dropna())

4

Q6. Keep only those rows that have at least 4 non-null values (dropna(thresh=4)).

In [19]:
data.dropna(thresh=4)

  Employee Name      Age Department   Salary       City  Experience
0           Raj     24.0  Marketing -99999.0      Delhi    -99999.0
1         Ayush      NaN         IT  80000.0     Mumbai         1.0
2       Anamika     20.0       None      NaN       Pune         0.0
3          Pari -99999.0         IT  55000.0       None         NaN
4       Rishabh     19.0     -99999  60000.0  Bangalore         1.0
5          Neha     28.0    Finance  90000.0     Mumbai         5.0
6        Vikram      NaN     -99999 -99999.0       None         8.0
7         Sneha     25.0       None  48000.0       Pune         3.0
8         Arjun -99999.0         IT      NaN  Bangalore         NaN
9         Priya     22.0    Finance  67000.0     Mumbai         1.0

Q7. Fill the missing values for both the "City" and "Age" columns simultaneously in a single fillna() call using a dictionary.

In [22]:
data.fillna({
    'City' : 'Unknown',
    'Age' : data['Age'].median()
})

  Employee Name      Age Department   Salary       City  Experience
0           Raj     24.0  Marketing -99999.0      Delhi    -99999.0
1         Ayush     21.0         IT  80000.0     Mumbai         1.0
2       Anamika     20.0       None      NaN       Pune         0.0
3          Pari -99999.0         IT  55000.0    Unknown         NaN
4       Rishabh     19.0     -99999  60000.0  Bangalore         1.0
5          Neha     28.0    Finance  90000.0     Mumbai         5.0
6        Vikram     21.0     -99999 -99999.0    Unknown         8.0
7         Sneha     25.0       None  48000.0       Pune         3.0
8         Arjun -99999.0         IT      NaN  Bangalore         NaN
9         Priya     22.0    Finance  67000.0     Mumbai         1.0