In [19]:
import pandas as pd
india_data = pd.DataFrame({
    "city" : ["Delhi","Mumbai","Banaras"],
    "population" : [37388,83737,23272]
})

us_data = pd.DataFrame({
    "city" : ["new york", "texas", "mexico"],
    "population" : [34738,92393,293837]
})
df = pd.concat([india_data,us_data], keys=["india","usa"])
df

             city  population
india 0     Delhi       37388
      1    Mumbai       83737
      2   Banaras       23272
usa   0  new york       34738
      1     texas       92393
      2    mexico      293837

In [20]:
df.loc['india']

      city  population
0    Delhi       37388
1   Mumbai       83737
2  Banaras       23272

In [ ]:
df1 = pd.read_csv("../datasets/nyc_weather.csv")
df2 = df1.fillna({"Events" : "Clear"})
df2.groupby("Events").size()

Events
Clear       22
Fog-Snow     2
Rain         4
Snow         3
dtype: int64