Practice Exercises — Data Shifting & Lag Analysis (shift())
Q1: Downward Shift Inspection
Load fb.csv and apply shift(1) to the DataFrame — what values will appear in the first row?

Q2: Upward Shift Inspection
What values will appear in the last row of the Series produced by df['Price'].shift(-1)?

Q3: Creating a Lagged Price Column
Create a new column named 'Prev Day Price' in the DataFrame using shift(1) on the 'Price' column.

Q4: Calculating Daily Price Change
Create a new column named 'Price Change' calculated as the current day's price minus the previous day's price.

Q5: Calculating 3-Day Return Percentage
Create a new column named '3 day return %' that calculates the 3-day percentage return using shift(3).

In [4]:
import pandas as pd
df = pd.read_csv("../datasets/fb.csv",parse_dates=['Date'],index_col='Date')
df.shift(1)

C:\Users\ap504\AppData\Local\Temp\ipykernel_30744\541852814.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("../datasets/fb.csv",parse_dates=['Date'],index_col='Date')

             Price
Date
2017-08-15     NaN
2017-08-16  171.00
2017-08-17  170.00
2017-08-18  166.91
2017-08-21  167.41
2017-08-22  167.78
2017-08-23  169.64
2017-08-24  168.71
2017-08-25  167.74
2017-08-28  166.32

In [5]:
df['Price'].shift(-1)

Date
2017-08-15    170.00
2017-08-16    166.91
2017-08-17    167.41
2017-08-18    167.78
2017-08-21    169.64
2017-08-22    168.71
2017-08-23    167.74
2017-08-24    166.32
2017-08-25    167.24
2017-08-28       NaN
Name: Price, dtype: float64

In [8]:
df['Prev Day Price'] = df['Price'].shift(1)
df

             Price  Prev Day Price
Date
2017-08-15  171.00             NaN
2017-08-16  170.00          171.00
2017-08-17  166.91          170.00
2017-08-18  167.41          166.91
2017-08-21  167.78          167.41
2017-08-22  169.64          167.78
2017-08-23  168.71          169.64
2017-08-24  167.74          168.71
2017-08-25  166.32          167.74
2017-08-28  167.24          166.32

In [11]:
df['Price Change'] = df['Price'] - df['Prev Day Price']
df

             Price  Prev Day Price  Price Change
Date
2017-08-15  171.00             NaN           NaN
2017-08-16  170.00          171.00         -1.00
2017-08-17  166.91          170.00         -3.09
2017-08-18  167.41          166.91          0.50
2017-08-21  167.78          167.41          0.37
2017-08-22  169.64          167.78          1.86
2017-08-23  168.71          169.64         -0.93
2017-08-24  167.74          168.71         -0.97
2017-08-25  166.32          167.74         -1.42
2017-08-28  167.24          166.32          0.92

In [13]:
df["3 day return %"] = (df['Price'] - df['Price'].shift(3))*100/df['Price'].shift(3)
df

             Price  Prev Day Price  Price Change  3 day return %
Date
2017-08-15  171.00             NaN           NaN             NaN
2017-08-16  170.00          171.00         -1.00             NaN
2017-08-17  166.91          170.00         -3.09             NaN
2017-08-18  167.41          166.91          0.50       -2.099415
2017-08-21  167.78          167.41          0.37       -1.305882
2017-08-22  169.64          167.78          1.86        1.635612
2017-08-23  168.71          169.64         -0.93        0.776537
2017-08-24  167.74          168.71         -0.97       -0.023841
2017-08-25  166.32          167.74         -1.42       -1.957086
2017-08-28  167.24          166.32          0.92       -0.871318