Question 1 (read_sql_query): Write a custom SQL query on the weather_data table to fetch only those rows where Temperature is greater than 30.

Question 2 (rename): Read the weather_data table and rename its Temperature column to Temp_F using the rename() method.

Question 3 (to_sql — new scenario): Create a small new DataFrame with 3 students' names and marks, then save it into the database as a new table named students.

Question 4 (read_sql — general version): Read the students table back from the database using read_sql() (use the general version, neither read_sql_table nor read_sql_query).

Question 5 (read_sql — query use case): Use read_sql() by passing a SQL query instead of a table name to extract days where Events = 'Rain' from weather_data

In [18]:
import pandas as pd
from sqlalchemy import create_engine, text
weather_df = pd.read_csv("../datasets/weather_data.csv")
weather_df.to_sql("weather_data", con=engine, if_exists="replace", index=False)

engine = create_engine("sqlite:///../datasets/customer_db.db")

In [19]:
query = text("SELECT * FROM weather_data WHERE Temperature > 30")

with engine.connect() as conn:
    df_high_temp = pd.read_sql_query(query, con=conn)

df_high_temp

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/7/2017         32.0        NaN    Rain
2  1/10/2017         34.0        8.0  Cloudy
3  1/11/2017         40.0       12.0   Sunny

In [20]:
df_weather = pd.read_sql_table("weather_data", con=engine)
df_weather.rename(columns={"Temperature": "Temp_F"}, inplace=True)
df_weather

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0    None
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN    None
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [21]:
students_df = pd.DataFrame(
    {"name": ["Aarav", "Ayush", "Pari"], "marks": [88, 95, 82]}
)

students_df.to_sql("students", con=engine, if_exists="replace", index=False)

3

In [22]:
df_students = pd.read_sql("students", con=engine)
df_students

    name  marks
0  Aarav     88
1  Ayush     95
2   Pari     82

In [24]:
query_rain = text("SELECT * FROM weather_data WHERE Event = 'Rain'")

with engine.connect() as conn:
    df_rainy_days = pd.read_sql(query_rain, con=conn)

df_rainy_days

        day  temperature  windspeed event
0  1/1/2017         32.0        6.0  Rain
1  1/7/2017         32.0        NaN  Rain