In [4]:
import pandas as pd
student_df = pd.DataFrame({
    "roll_no" : [1,2,3],
    "name" : ["Ritik","Pari","juju"]
})

marks_df = pd.DataFrame({
    "roll_no" : [1,2,4],
    "marks" : [83,91,76]
})

df = pd.merge(student_df,marks_df, on='roll_no')
df

   roll_no   name  marks
0        1  Ritik     83
1        2   Pari     91

In [5]:
df1 = pd.merge(student_df,marks_df, on='roll_no',how='outer')
df1

   roll_no   name  marks
0        1  Ritik   83.0
1        2   Pari   91.0
2        3   juju    NaN
3        4    NaN   76.0

Question 5 (Combined — merge + pivot_table):
Question 1 wale students_df aur marks_df ko merge karo (inner join), phir result pe pivot_table() lagाओ jisme name index ho aur marks ka simple table dikhे (aggfunc mean se, chahe ek hi value ho).

In [9]:
result = df.pivot_table(index='name', values='marks', aggfunc='mean')
print(result)

       marks
name
Pari    91.0
Ritik   83.0