In [1]:
import pandas as pd
df = pd.read_csv("../datasets/nyc_weather.csv")
df.set_index('EST', inplace=True)
df.loc['1/9/2016':'1/12/2016']

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,
1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235

Question 1 (Selection + Row Selection):
nyc_weather.csv load karo (fresh se, df = pd.read_csv(...)). Uske index ko EST column bana do. Fir .loc use karke sirf 1/9/2016 se 1/12/2016 tak ki rows nikaalo.

In [2]:
df[df.Humidity > 50]['Temperature'].mean()

np.float64(38.06666666666667)

Question 2 (Filtering + Statistics):
Same dataset mein — sirf wahi rows nikaalo jaha Humidity 50 se zyada ho, aur un rows ka Temperature ka average nikaalo.

In [4]:
import pandas as pd
df = pd.read_csv("../datasets/nyc_weather.csv")
df["EST"][df.WindSpeedMPH == df["WindSpeedMPH"].max()]

22    1/23/2016
Name: EST, dtype: object

nyc_weather.csv mein — sabse zyada WindSpeedMPH wale din ka sirf EST (date) nikaalo (Series wala tarika, jo humne pehle kiya tha)

In [6]:
df = pd.read_csv("../datasets/stock_data.csv",na_values=["not available","n.a.","-1","-1.00"])
df

  ticker    eps  revenue   price         people
0  GOOGL  27.82     87.0   845.0     larry page
1    WMT   4.61    484.0    65.0            NaN
2   MSFT    NaN     85.0    64.0     bill gates
3   RIL     NaN     50.0  1023.0  mukesh ambani
4   TATA   5.60      NaN     NaN     ratan tata

Question 4 (DataFrame Creation + na_values):
stock_data.csv ko load karo aisa ki "not available" aur "n.a." dono NaN ban jaayein, sirf list wale tarike se (dictionary nahi).

In [ ]:
df.describe()
df.to_csv("cleaned_stock_data.csv", index=False)
df

  ticker    eps  revenue   price         people
0  GOOGL  27.82     87.0   845.0     larry page
1    WMT   4.61    484.0    65.0            NaN
2   MSFT    NaN     85.0    64.0     bill gates
3   RIL     NaN     50.0  1023.0  mukesh ambani
4   TATA   5.60      NaN     NaN     ratan tata

Question 5 (to_csv + describe):
Question 4 wale DataFrame ka describe() chalao. Fir usi DataFrame ko ek nayi file "cleaned_stock_data.csv" mein save karo, bina index ke.