## Step 1: Converting the Date Column to Proper Date Type

* `parse_dates=['col_name']` → Passing this inside `read_csv()` automatically converts the column to datetime format
* Replaces the need to call `pd.to_datetime()` separately afterwards as a shortcut

In [2]:
import pandas as pd
df = pd.read_csv("../datasets/weather_data.csv", parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

## Step 2: Setting Date as Index

* `set_index()` → Same previous concept; now that the date is in a proper datetime format, time-based operations (like `interpolate(method="time")`) will work correctly

In [3]:
df.set_index('day',inplace=True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## Handling Missing Values using fillna()

* `df.fillna(0)` → Replaces all missing (`NaN`) values across the entire DataFrame with `0`
* Dictionary Mapping → Replaces missing (`NaN`) values with column-specific defaults (e.g., numeric defaults for measurements and string defaults for categorical data)

In [4]:
new_df = df.fillna(0)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [5]:
new_df = df.fillna({
    'temperature' : 0,
    'windspeed' : 0,
    'event' : "no event"
})
new_df

            temperature  windspeed     event
day
2017-01-01         32.0        6.0      Rain
2017-01-04          0.0        9.0     Sunny
2017-01-05         28.0        0.0      Snow
2017-01-06          0.0        7.0  no event
2017-01-07         32.0        0.0      Rain
2017-01-08          0.0        0.0     Sunny
2017-01-09          0.0        0.0  no event
2017-01-10         34.0        8.0    Cloudy
2017-01-11         40.0       12.0     Sunny

## ffill() and bfill() — Filling Values from Adjacent Cells

* `ffill()` → Fill `NaN` with the previous (above) value (Forward Fill)
* `bfill()` → Fill `NaN` with the next (below) value (Backward Fill)
* `axis="columns"` → Fill horizontally from LEFT-to-RIGHT across columns within a row (less common use case)
*(Default is `axis="index"`, which fills vertically/top-to-bottom across rows)*

In [6]:
new_df = df.ffill()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [7]:
new_df = df.bfill()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [8]:
new_df = df.bfill(axis="columns")
new_df

C:\Users\ap504\AppData\Local\Temp\ipykernel_24076\2571378427.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df = df.bfill(axis="columns")

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         9.0       9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0       7.0     NaN
2017-01-07        32.0      Rain    Rain
2017-01-08       Sunny     Sunny   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.0       8.0  Cloudy
2017-01-11        40.0      12.0   Sunny

In [9]:
new_df = df.ffill(axis="columns")
new_df

C:\Users\ap504\AppData\Local\Temp\ipykernel_24076\989562250.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df = df.ffill(axis="columns")

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         NaN       9.0   Sunny
2017-01-05        28.0      28.0    Snow
2017-01-06         NaN       7.0     7.0
2017-01-07        32.0      32.0    Rain
2017-01-08         NaN       NaN   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.0       8.0  Cloudy
2017-01-11        40.0      12.0   Sunny

## limit Parameter — Restricting Fill Frequency

* `ffill(limit=1)` → Fills only 1 consecutive `NaN` value; subsequent `NaN`s remain unchanged
* Real-world use case: Ideal for filling small gaps (1-2 missing days), whereas filling large gaps (a week of missing data) would be misleading

In [10]:
new_df = df.ffill(limit=1)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## interpolate() — Filling Values Using Mathematical Estimation

* `method="time"` → Accurately estimates values based on actual date-index intervals *(requires the index to be a `DatetimeIndex`)*
* IMPORTANT: Calling `interpolate()` on text (`object` dtype) columns will trigger a warning
* FIX: Filter numeric columns first using `select_dtypes(include='number')`, then apply `interpolate()`
*(The `numeric_only=True` parameter is unreliable in this version — `select_dtypes` is the preferred approach)*

In [11]:
new_df = df.select_dtypes(include='number').interpolate(method="time")
new_df

            temperature  windspeed
day
2017-01-01    32.000000       6.00
2017-01-04    29.000000       9.00
2017-01-05    28.000000       8.00
2017-01-06    30.000000       7.00
2017-01-07    32.000000       7.25
2017-01-08    32.666667       7.50
2017-01-09    33.333333       7.75
2017-01-10    34.000000       8.00
2017-01-11    40.000000      12.00

## dropna() — Dropping Rows with Missing Data

* `dropna()` → Drops the entire row if even a SINGLE `NaN` is present (most aggressive/strict)
* `dropna(how='all')` → Drops the row only if ALL values are `NaN` (least aggressive)
* `dropna(thresh=n)` → Requires at least `n` non-NaN values for the row to be kept, otherwise drops it (balanced approach)

In [12]:
new_df = df.dropna()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [13]:
new_df = df.dropna(how='all')
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [14]:
new_df = df.dropna(thresh=2)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## reindex() — Explicitly Adding Missing Dates

* `pd.date_range(start, end)` → Generates a COMPLETE sequence of dates between the start and end dates (no skipped days)
* `reindex(idx)` → Forces the DataFrame to conform to this complete date sequence
* Dates absent in the original data are automatically populated with `NaN` across columns
* Real-world use case: Reveals missing time-series dates explicitly as `NaN` instead of leaving gaps undetected, allowing for proper data handling

In [15]:
dt = pd.date_range("2017-01-01", "2017-01-11")
idx = pd.DatetimeIndex(dt)

df = df.reindex(idx)
df

            temperature  windspeed   event
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny