## Basic `concat()` — Stacking DataFrames Vertically (Row-Wise)

* `pd.concat([df1, df2])` → Stacks multiple DataFrames on top of each other along the row axis (`axis=0` by default)
* Keeps each DataFrame's original index numbers by default, which can result in duplicate index entries across the concatenated result
* `ignore_index=True` → Re-indexes the combined DataFrame sequentially from `0` to `N-1`, preventing index clashes and duplicate row labels

In [1]:
import pandas as pd

india_weather = pd.DataFrame({
    'city': ["Delhi", "mumbai", "Banglore"],
    'temperature': [32, 28, 45],
    'humidity': [60, 80, 78]
})

india_weather

usa_weather = pd.DataFrame({
    'city': ["new york", "chicago", "londob"],
    'temperature': [21, 12, 29],
    'humidity': [68, 65, 78]
})

usa_weather

df = pd.concat([india_weather,usa_weather], ignore_index=True)
df

       city  temperature  humidity
0     Delhi           32        60
1    mumbai           28        80
2  Banglore           45        78
3  new york           21        68
4   chicago           12        65
5    londob           29        78

## `keys` Parameter — Tracking Data Origins with MultiIndex

* `keys=['label1', 'label2']` → Assigns a top-level label to each concatenated DataFrame, creating a **MultiIndex** (hierarchical index) on the rows
* Enables source-level filtering using `.loc['label1']` to isolate and query data originating from a specific source DataFrame
* **Real-World Use Case:** Useful when aggregating data from distinct batches, regions, or time periods (e.g., `'Q1_Data'`, `'Q2_Data'`) while retaining full traceability of each row's origin

In [2]:
df = pd.concat([india_weather, usa_weather], keys=['india', 'usa'])
df

             city  temperature  humidity
india 0     Delhi           32        60
      1    mumbai           28        80
      2  Banglore           45        78
usa   0  new york           21        68
      1   chicago           12        65
      2    londob           29        78

In [ ]:
df.loc['india']

## axis=1 — Concatenating Columns Side-by-Side

* Default `axis=0` (appends rows vertically, top-to-bottom)
* `axis=1` → Joins DataFrames horizontally from LEFT-to-RIGHT (adds columns, aligned by row index)
* **Real-World Use Case:** When different files contain different features/columns for the same records (e.g., one file contains temperature data and another contains windspeed data for the same set of cities), joining them side-by-side merges them into a single comprehensive DataFrame

In [ ]:
temperature_df = pd.DataFrame({
    'city' : ['mumbai','delhi','jaipur'],
    'temprature' : [32,40,43]
})
temperature_df

windspeed_df = pd.DataFrame({
    'city' : ['mumbai','delhi','jaipur'],
    'windspeed' : [7,12,9]
})
windspeed_df

df = pd.concat([temperature_df,windspeed_df], axis=1)
df

## Adding a Series to a DataFrame (Using concat)

* `pd.Series([...], name='col_name')` → Create a Series where `name` defines the destination column header
* Concatenating with `axis=1` appends this Series as a brand-new column along the right side of the DataFrame

In [ ]:
s = pd.Series(['Humid','Dry','Rain'], name='event')
df = pd.concat([temperature_df,s], axis=1)
df