## Basic merge() = Inner Join (Default)
- pd.merge(df1, df2, on='column') → sirf wahi rows aayengi jo DONO DataFrames mein match karti hain
- Order of rows/DataFrames mein matter nahi karta, sirf matching VALUES pe based hota hai
- Default behavior "inner join" hi hota hai (how='inner' likhne ki zarurat nahi)

In [35]:
import pandas as pd
df1 = pd.DataFrame({
    'city' : ['new york','chicago','orlando'],
    'temperature' : [21,14,25]
})
df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           25

In [ ]:
df2 = pd.DataFrame({
    'city' : ['chicago','new york','orlando'],
    'humidity' : [56,38,57]
})
df2

In [ ]:
df3 = pd.merge(df1,df2,on='city')
df3

## Outer Join
- how='outer' → SAARI rows aayengi (dono taraf se), match ho ya na ho
- Jaha match nahi milega, wahan NaN aa jaayega

In [ ]:
df4 = pd.DataFrame({
    'city' : ['new york','san francisco','chicago','orlando'],
    'temperature' : [21,14,25,28]
})
df4

In [ ]:
df5 = pd.DataFrame({
    'city' : ['ireland','chicago','new york','orlando'],
    'humidity' : [56,38,57,65]
})
df5

In [21]:
df6 = pd.merge(df4,df5,on='city',how='outer')
df6

            city  temperatur  humidity
0        chicago        25.0      38.0
1        ireland         NaN      56.0
2       new york        21.0      57.0
3        orlando        28.0      65.0
4  san francisco        14.0       NaN

## indicator=True — Row Ka Origin Batana
- Ek naya column "_merge" add hota hai
- Values: "left_only", "right_only", ya "both"

In [22]:
df6 = pd.merge(df4,df5,on='city',how='outer',indicator=True)
df6

            city  temperatur  humidity      _merge
0        chicago        25.0      38.0        both
1        ireland         NaN      56.0  right_only
2       new york        21.0      57.0        both
3        orlando        28.0      65.0        both
4  san francisco        14.0       NaN   left_only

## Left Join aur Right Join
- how='left' → LEFT DataFrame ki saari rows (jo sirf right mein hai, wo exclude ho jaayegi)
- how='right' → RIGHT DataFrame ki saari rows (jo sirf left mein hai, wo exclude ho jaayegi)
- Jo match nahi hota us taraf, NaN aa jaata hai

In [ ]:
df7 = pd.merge(df4,df5,on='city',how='left')
df7

In [32]:
df8 = pd.merge(df4,df5,on='city',how='right')
df8

       city  temperatur  humidity
0   ireland         NaN        56
1   chicago        25.0        38
2  new york        21.0        57
3   orlando        28.0        65

## suffixes — Same-Naam Columns Ka Conflict Solve Karna
- Agar dono DataFrames mein same column naam hai (jaise dono mein temperature/humidity), Pandas confuse ho jaata
- Default: automatically "_x" (left) aur "_y" (right) laga deta hai
- suffixes=('_custom1', '_custom2') → apna naam de sakte ho

In [ ]:
df9 = pd.DataFrame({
    'city' : ['new york','chicago','orlando'],
    'temperature' : [21,14,25],
    'humidity' : [56,38,55]
})
df9

       city  temperatur  humidity
0  new york          21        56
1   chicago          14        38
2   orlando          25        55

In [ ]:
df10 = pd.DataFrame({
    'city' : ['chicago','new york','orlando'],
    'humidity' : [38,56,65],
    'temperature' : [11,21,25],
})
df10

       city  humidity  temperatur
0   chicago        38          11
1  new york        56          21
2   orlando        65          25

In [30]:
df11 = pd.merge(df9,df10,on='city')
df11

       city  temperatur_x  humidity_x  humidity_y  temperatur_y
0  new york            21          56          56            21
1   chicago            14          38          38            11
2   orlando            25          55          65            25

In [31]:
df12 = pd.merge(df9,df10,on='city', suffixes=('_left','_right'))
df12

       city  temperatur_left  humidity_left  humidity_right  temperatur_right
0  new york               21             56              56                21
1   chicago               14             38              38                11
2   orlando               25             55              65                25