# Lecture 22: shift() — Moving Data Forward or Backward

## shift(n)
- df.shift(1) → moves all values DOWN by 1 row (first row becomes NaN)
- df.shift(-1) → moves all values UP by 1 row (last row becomes NaN)
- Useful for comparing current value with previous/next value

In [36]:
import pandas as pd
df = pd.read_csv("../datasets/fb.csv",parse_dates=['Date'],index_col='Date')
df

C:\Users\ap504\AppData\Local\Temp\ipykernel_27652\2745627973.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("../datasets/fb.csv",parse_dates=['Date'],index_col='Date')

             Price
Date
2017-08-15  171.00
2017-08-16  170.00
2017-08-17  166.91
2017-08-18  167.41
2017-08-21  167.78
2017-08-22  169.64
2017-08-23  168.71
2017-08-24  167.74
2017-08-25  166.32
2017-08-28  167.24

In [37]:
df.shift(2)

             Price
Date
2017-08-15     NaN
2017-08-16     NaN
2017-08-17  171.00
2017-08-18  170.00
2017-08-21  166.91
2017-08-22  167.41
2017-08-23  167.78
2017-08-24  169.64
2017-08-25  168.71
2017-08-28  167.74

In [14]:
df.shift(-1)

             Price
Date
2017-08-15  170.00
2017-08-16  166.91
2017-08-17  167.41
2017-08-18  167.78
2017-08-21  169.64
2017-08-22  168.71
2017-08-23  167.74
2017-08-24  166.32
2017-08-25  167.24
2017-08-28     NaN

## Common Real-World Uses
- Previous day price: df['Price'].shift(1)
- Daily price change: df['Price'] - df['Price'].shift(1)
- 5-day return %: (df['Price'] - df['Price'].shift(5)) * 100 / df['Price'].shift(5)

In [16]:
df['prev day price'] = df['Price'].shift(1)
df

             Price  prev day price
Date
2017-08-15  171.00             NaN
2017-08-16  170.00          171.00
2017-08-17  166.91          170.00
2017-08-18  167.41          166.91
2017-08-21  167.78          167.41
2017-08-22  169.64          167.78
2017-08-23  168.71          169.64
2017-08-24  167.74          168.71
2017-08-25  166.32          167.74
2017-08-28  167.24          166.32

In [18]:
df['1 Day change'] = df['Price'] - df['prev day price']
df

             Price  prev day price  1 Day change
Date
2017-08-15  171.00             NaN           NaN
2017-08-16  170.00          171.00         -1.00
2017-08-17  166.91          170.00         -3.09
2017-08-18  167.41          166.91          0.50
2017-08-21  167.78          167.41          0.37
2017-08-22  169.64          167.78          1.86
2017-08-23  168.71          169.64         -0.93
2017-08-24  167.74          168.71         -0.97
2017-08-25  166.32          167.74         -1.42
2017-08-28  167.24          166.32          0.92

In [20]:
df['5 day % return'] = (df['Price'] - df['Price'].shift(5))*100/df['Price'].shift(5)
df

             Price  prev day price  1 Day change  5 day % return
Date
2017-08-15  171.00             NaN           NaN             NaN
2017-08-16  170.00          171.00         -1.00             NaN
2017-08-17  166.91          170.00         -3.09             NaN
2017-08-18  167.41          166.91          0.50             NaN
2017-08-21  167.78          167.41          0.37             NaN
2017-08-22  169.64          167.78          1.86       -0.795322
2017-08-23  168.71          169.64         -0.93       -0.758824
2017-08-24  167.74          168.71         -0.97        0.497274
2017-08-25  166.32          167.74         -1.42       -0.651096
2017-08-28  167.24          166.32          0.92       -0.321850

## tshift(n) — Shift the INDEX (not the data)
- Shifts the DatetimeIndex forward/backward by n periods
- Data stays in same rows, only timestamps change
- shift() moves DATA, df.shift(1, freq="B") moves TIMESTAMPS

In [31]:
df = df[['Price']]
df

             Price
2017-08-15  171.00
2017-08-16  170.00
2017-08-17  166.91
2017-08-18  167.41
2017-08-21  167.78
2017-08-22  169.64
2017-08-23  168.71
2017-08-24  167.74
2017-08-25  166.32
2017-08-28  167.24

In [32]:
df_shifted = df.shift(1, freq="B")
df_shifted

             Price
2017-08-16  171.00
2017-08-17  170.00
2017-08-18  166.91
2017-08-21  167.41
2017-08-22  167.78
2017-08-23  169.64
2017-08-24  168.71
2017-08-25  167.74
2017-08-28  166.32
2017-08-29  167.24