In [2]:
import pandas as pd 
df = pd.read_csv("../datasets/stock_data.csv")
df

  ticker            eps  revenue price         people
0  GOOGL          27.82       87   845     larry page
1    WMT           4.61      484    65           n.a.
2   MSFT             -1       85    64     bill gates
3   RIL   not available       50  1023  mukesh ambani
4   TATA            5.6       -1  n.a.     ratan tata

header=None and names=

header=None → The first row in the file is actual data, not a header
names=[...] → Manually provide column names

In [3]:
df = pd.read_csv("../datasets/stock_data.csv",header=None)
df

        0              1        2      3              4
0  ticker            eps  revenue  price         people
1   GOOGL          27.82       87    845     larry page
2     WMT           4.61      484     65           n.a.
3    MSFT             -1       85     64     bill gates
4    RIL   not available       50   1023  mukesh ambani
5    TATA            5.6       -1   n.a.     ratan tata

In [4]:
df = pd.read_csv("../datasets/stock_data.csv", names = ["ticker", "eps","revenue","price", "people"])
df

   ticker            eps  revenue  price         people
0  ticker            eps  revenue  price         people
1   GOOGL          27.82       87    845     larry page
2     WMT           4.61      484     65           n.a.
3    MSFT             -1       85     64     bill gates
4    RIL   not available       50   1023  mukesh ambani
5    TATA            5.6       -1   n.a.     ratan tata

nrows — Reading a limited number of rows (for testing large files)

In [5]:
df = pd.read_csv("../datasets/stock_data.csv", nrows=2)
df

  ticker    eps  revenue  price      people
0  GOOGL  27.82       87    845  larry page
1    WMT   4.61      484     65        n.a.

na_values — Converting messy data into NaN :

Using a List → Applies the same rule across all columns
Using a Dictionary → Applies column-specific rules to each column

In [6]:
df = pd.read_csv("../datasets/stock_data.csv", na_values=["not available", "n.a."])
df

  ticker    eps  revenue   price         people
0  GOOGL  27.82       87   845.0     larry page
1    WMT   4.61      484    65.0            NaN
2   MSFT  -1.00       85    64.0     bill gates
3   RIL     NaN       50  1023.0  mukesh ambani
4   TATA   5.60       -1     NaN     ratan tata

In [7]:
df = pd.read_csv("../datasets/stock_data.csv",na_values={
    'eps' : ["not available", "n.a."],
    'revenue' : ["not available", "n.a.", -1],
    'people' : [" not available", "n.a."]
})
df

  ticker    eps  revenue price         people
0  GOOGL  27.82     87.0   845     larry page
1    WMT   4.61    484.0    65            NaN
2   MSFT  -1.00     85.0    64     bill gates
3   RIL     NaN     50.0  1023  mukesh ambani
4   TATA   5.60      NaN  n.a.     ratan tata

to_csv() — Saving a DataFrame to a CSV file :

index=False → Excludes the row index from being saved (best practice)
columns=[...] → Saves only specific columns
header=False → Excludes column names from being saved

In [8]:
df.to_csv("new.csv")
df

  ticker    eps  revenue price         people
0  GOOGL  27.82     87.0   845     larry page
1    WMT   4.61    484.0    65            NaN
2   MSFT  -1.00     85.0    64     bill gates
3   RIL     NaN     50.0  1023  mukesh ambani
4   TATA   5.60      NaN  n.a.     ratan tata

In [9]:
df.to_csv("new.csv",index=False)
df

  ticker    eps  revenue price         people
0  GOOGL  27.82     87.0   845     larry page
1    WMT   4.61    484.0    65            NaN
2   MSFT  -1.00     85.0    64     bill gates
3   RIL     NaN     50.0  1023  mukesh ambani
4   TATA   5.60      NaN  n.a.     ratan tata

In [10]:
df.columns

Index(['ticker', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [11]:
df.to_csv("new.csv",columns=['ticker', 'eps'])
df

  ticker    eps  revenue price         people
0  GOOGL  27.82     87.0   845     larry page
1    WMT   4.61    484.0    65            NaN
2   MSFT  -1.00     85.0    64     bill gates
3   RIL     NaN     50.0  1023  mukesh ambani
4   TATA   5.60      NaN  n.a.     ratan tata

In [12]:
df.to_csv("new.csv", header=False)
df

  ticker    eps  revenue price         people
0  GOOGL  27.82     87.0   845     larry page
1    WMT   4.61    484.0    65            NaN
2   MSFT  -1.00     85.0    64     bill gates
3   RIL     NaN     50.0  1023  mukesh ambani
4   TATA   5.60      NaN  n.a.     ratan tata

read_excel() and converters
converters → Transforms every value in a specific column using a custom function

In [13]:
df = pd.read_excel("../datasets/stock_data.xlsx", sheet_name= "Sheet1")
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [14]:
def convert_people_cell(cell):
    if cell == "n.a." :
        return "sam walton"
    return cell
df = pd.read_excel("../datasets/stock_data.xlsx", sheet_name="Sheet1" , converters={'people':convert_people_cell})
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65     sam walton
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

to_excel() — Controlling position using startrow / startcol

nrows — Reading a limited number of rows (for testing large files)

In [15]:
df.to_excel("new.xlsx",sheet_name= 'stocks')
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65     sam walton
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [16]:
df.to_excel("new.xlsx",sheet_name= "stocks", startrow=1, startcol=2)

ExcelWriter — Saving multiple sheets in a single file (multiple DataFrames)

In [17]:
df_stocks = pd.DataFrame({
    'TICKER' : ['GOOGLE', 'APPLE'],
    'EPS' : [34,23],
    'ROE' : [54, 63]
})

df_weather = pd.DataFrame({
    'DATE' : ['1/1/2017','1/2/2017','1/3/2017'],
    'TEMPRATURE' : [32,30,28],
    'EVENTS' : ['SUNNY', 'CLOUDY', 'RAIN']
})

with pd.ExcelWriter('Stock_Weather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_weather.to_excel(writer, sheet_name="weather")